Repository Automattic/wp-desktop, pull requests merged in 2018-06, with the labels that each got.

#440 develop-next
  Makefile
  circle.yml
  desktop-config/config-base.json
  desktop-config/config-dev.json
  desktop-config/config-development.json
  desktop-config/config-release.json
  desktop-config/config-test.json
  desktop-config/config-updater.json
  desktop/env.js
  desktop/server/index.js
  desktop/test/boot.js
  desktop/window-handlers/external-links/index.js
  package.json
  public_desktop/desktop-app.js
  public_desktop/preferences.html
  resource/build-config/build.json
  resource/build-config/calypso-ignore.js
  resource/build-config/calypso.json
  resource/build-config/dmg.json
  resource/build-config/win32-package.json
  resource/build-config/windows-nsi.tpl
  resource/build-scripts/build-config-file.js
  resource/build-scripts/code-sign-win.js
  resource/build-scripts/package-dmg.js
  resource/build-scripts/package-linux.js
  resource/build-scripts/rename-with-version-osx.js
  resource/build-scripts/rename-with-version-win.js
  resource/build-scripts/wpcom-uninstall.scpt
  resource/calypso/secrets.json.enc
  resource/certificates/mac.p12.enc
  resource/certificates/win.p12.enc
  resource/developer-id.p12.enc
  resource/image/linux/icon_128x128.png
  resource/image/linux/icon_128x128@2x.png
  resource/image/linux/icon_16x16.png
  resource/image/linux/icon_16x16@2x.png
  resource/image/linux/icon_256x256.png
  resource/image/linux/icon_256x256@2x.png
  resource/image/linux/icon_32x32.png
  resource/image/linux/icon_32x32@2x.png
  resource/image/linux/icon_512x512.png
  resource/image/linux/icon_512x512@2x.png
  resource/image/mac/app-icon.icns
  resource/image/mac/dmg-background/background.png
  resource/image/mac/dmg-background/background@2x.png
  resource/image/mac/dmg-icon.icns
  resource/image/win/wordpress.ico
  resource/lib/config.js
  resource/lib/spellchecker.js
  resource/lib/tools.js
  resource/linux/wpcom.desktop
  resource/platform/darwin.js
  resource/platform/linux.js
  resource/platform/win32.js
  resource/test/osx.js
  resource/win32-secrets-tar.gz.enc
  test/appStart.js
  webpack.config.js
  webpack.config.test.js
Labels: [Status] Ready to Merge

#451 Fix webhook URL it is using the wrong one
  circle.yml
Labels: [Pri] High, [Type] Enhancement

#452 Move CircleCI config into correct location
  .circleci/config.yml
Labels: [Status] Needs Review, [Type] Task

#455 CircleCI: build on tags
  .circleci/config.yml
Labels: [Status] Needs Review

#461 CircleCI: Cache nvm usage
  .circleci/config.yml
Labels: [Status] Ready to Merge, [Type] Enhancement, [Type] Task

#462 CircleCI: Improve npm cache and install
  .circleci/config.yml
  package-lock.json
  package.json
Labels: [Status] Ready to Merge, [Type] Enhancement, [Type] Task

#465 Quit app via menu should quit app
  desktop/lib/menu/app-menu.js
  package-lock.json
Labels: [Platform] Windows, [Status] Needs Review
