Repository Automattic/wp-desktop, pull requests merged in 2018-07, with the labels that each got.

#466 Try bashrc file for shared setup
  .circleci/bashrc
  .circleci/config.yml
Labels: [Status] Needs Review, [Type] Enhancement

#464 Fix RCE in Electron Windows
  desktop-config/config-base.json
  desktop/lib/window-manager/index.js
Labels: [Pri] High

#473 Match 10.5.0 and v10.5.0 node versions
  Makefile
Labels: [Status] Needs Review, [Type] Enhancement

#474 Update secrets.md docs to recommend a Type: native OAuth token
  docs/secrets.md
Labels: [Status] Ready to Merge

#477 Upgrade Babel to 7.0.0 beta 53
  babel.config.js
  package-lock.json
  package.json
Labels: [Status] Needs Review

#447 Improve spell checker
  .circleci/config.yml
  desktop/env.js
  desktop/lib/menu/editor-context-menu.js
  desktop/lib/menu/general-context-menu.js
  package-lock.json
  package.json
  public_desktop/desktop-app.js
  public_desktop/preferences.html
  public_desktop/preload.js
  test/appStart.js
Labels: [Status] Needs Review, [Type] Enhancement
