Repository Automattic/wp-desktop, pull requests merged in 2020-01, with the labels that each got.

#743 Use the @automattic/calypso-polyfills package to polyfill the JS environment
  babel.config.js
  desktop/index.js
  package-lock.json
  package.json
  webpack.shared.js
Labels: [Status] Needs Review

#742 [.gitignore] Ignore Decrypted Certs
  .gitignore
Labels: [Status] Needs Review

#732 [e2e] Fix logout issue in e2e tests
  test/tests/e2e.js
  test/tests/lib/pages/editor-page.js
  test/tests/lib/pages/login-page.js
  test/tests/lib/pages/reader-page.js
Labels: [Status] Ready to Merge

#753 Merge Release/4.7.0 into Develop
  package-lock.json
  package.json
Labels: Releases
