Repository Automattic/wp-desktop, pull requests merged in 2020-04, with the labels that each got.

#823 merge: merge release/5.0.1 into develop
  desktop/app-handlers/updater/auto-updater/index.js
  desktop/lib/app-quit/index.js
  desktop/lib/platform/windows/index.js
  package-lock.json
  package.json
  test/run/run-e2e-tests.js
Labels: Releases

#822 improvement(tooling): add Windows dev tooling
  .circleci/config.yml
  .gitignore
  Dockerfile
  Makefile
  docs/development.md
  package.json
Labels: [Platform] Windows, [Status] Needs Review

#816 feat(logging): archive and export logs [3]
  desktop/lib/archiver/index.js
  desktop/lib/menu/help-menu.js
  desktop/window-handlers/get-logs/index.js
  package-lock.json
  package.json
Labels: [Status] Needs Review

#815 feat(logging): replace debug with custom logger
  desktop/app-handlers/crash-reporting/index.js
  desktop/app-handlers/exceptions/index.js
  desktop/app-handlers/logging/index.js
  desktop/app-handlers/logging/ipc-handler/index.js
  desktop/app-handlers/printer/index.js
  desktop/app-handlers/updater/auto-updater/index.js
  desktop/app-handlers/updater/index.js
  desktop/app-handlers/updater/manual-updater/index.js
  desktop/app.js
  desktop/env.js
  desktop/lib/app-instance/index.js
  desktop/lib/archiver/index.js
  desktop/lib/calypso-commands/index.js
  desktop/lib/crash-tracker/index.js
  desktop/lib/debug-tools/README.md
  desktop/lib/debug-tools/index.js
  desktop/lib/desktop-analytics/index.js
  desktop/lib/logger/index.js
  desktop/lib/menu/help-menu.js
  desktop/lib/menu/index.js
  desktop/lib/platform/linux/index.js
  desktop/lib/platform/mac/index.js
  desktop/lib/platform/windows/index.js
  desktop/lib/settings/index.js
  desktop/lib/settings/settings-file.js
  desktop/lib/system/index.js
  desktop/lib/updater/index.js
  desktop/server/index.js
  desktop/server/server.js
  desktop/window-handlers/debug-tools/index.js
  desktop/window-handlers/external-links/index.js
  desktop/window-handlers/failed-to-load/index.js
  desktop/window-handlers/get-logs/index.js
  desktop/window-handlers/notifications/index.js
  package-lock.json
  package.json
  public_desktop/desktop-app.js
  public_desktop/preload.js
Labels: [Status] Needs Review

#814 feat(logging): persist and export application logs
  desktop/app-handlers/crash-reporting/index.js
  desktop/app-handlers/exceptions/index.js
  desktop/app-handlers/logging/index.js
  desktop/app-handlers/logging/ipc-handler/index.js
  desktop/app-handlers/printer/index.js
  desktop/app-handlers/updater/auto-updater/index.js
  desktop/app-handlers/updater/index.js
  desktop/app-handlers/updater/manual-updater/index.js
  desktop/app.js
  desktop/env.js
  desktop/lib/app-instance/index.js
  desktop/lib/archiver/index.js
  desktop/lib/calypso-commands/index.js
  desktop/lib/crash-tracker/index.js
  desktop/lib/debug-tools/README.md
  desktop/lib/debug-tools/index.js
  desktop/lib/desktop-analytics/index.js
  desktop/lib/logger/index.js
  desktop/lib/logger/namespaces/index.js
  desktop/lib/logger/package-lock.json
  desktop/lib/menu/help-menu.js
  desktop/lib/menu/index.js
  desktop/lib/platform/linux/index.js
  desktop/lib/platform/mac/index.js
  desktop/lib/platform/windows/index.js
  desktop/lib/settings/index.js
  desktop/lib/settings/settings-file.js
  desktop/lib/state/index.js
  desktop/lib/system/index.js
  desktop/lib/updater/index.js
  desktop/server/index.js
  desktop/server/server.js
  desktop/window-handlers/debug-tools/index.js
  desktop/window-handlers/external-links/index.js
  desktop/window-handlers/failed-to-load/index.js
  desktop/window-handlers/get-logs/index.js
  desktop/window-handlers/notifications/index.js
  package-lock.json
  package.json
  public_desktop/desktop-app.js
  public_desktop/preload.js
  test/run/run-e2e-tests.js
Labels: [Status] Needs Review

#831 chore: rename built artifacts
  package.json
Labels: [Status] Needs Review

#846 build: deploy with ghr
  .circleci/config.yml
  Makefile
Labels: [Status] Needs Review

#848 build: automate Github release notes
  .circleci/config.yml
  make-changelog.sh
Labels: [Status] Needs Review

#845 chore(auto-updater): disable auto-updater in DEBUG mode
  desktop/app-handlers/updater/auto-updater/index.js
  test/run/run-e2e-tests.js
Labels: [Status] Needs Review

#849 chore: merge release/5.1.0-beta1
  package-lock.json
  package.json
Labels: Releases
